title: "Unflattening: A data science blog"
description: Data science-related blog
permalink: ':title/'
baseurl: ""
url: ""
site-twitter:

# Author Settings
author: Gabriel Fritz Sluzala
author-img: gabriel-fritz-sluzala.png
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: 
social-facebook: 
social-github: GabrielFritz
social-linkedin: gabriel-fritz-sluzala
social-email: gabrielfritzsluzala@gmail.com

# Disqus
discus-identifier: 

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
